// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerBackup.Data;

#nullable disable

namespace ServerBackup.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ServerBackup.Data.Entities.AuditLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ServerBackup.Data.Entities.BlobEntity", b =>
                {
                    b.Property<string>("BlobId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Compression")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LenPlain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LenStored")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Offset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BlobId");

                    b.HasIndex("PackId");

                    b.ToTable("Blobs");
                });

            modelBuilder.Entity("ServerBackup.Data.Entities.JobEntity", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.HasIndex("PlanId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ServerBackup.Data.Entities.JobLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobLogs");
                });

            modelBuilder.Entity("ServerBackup.Data.Entities.PackEntity", b =>
                {
                    b.Property<string>("PackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackId");

                    b.ToTable("Packs");
                });

            modelBuilder.Entity("ServerBackup.Data.Entities.PlanEntity", b =>
                {
                    b.Property<string>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CronSchedule")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RetentionPolicyJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePathsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("ServerBackup.Data.Entities.SnapshotEntity", b =>
                {
                    b.Property<string>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootTreeBlobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SnapshotId");

                    b.HasIndex("PlanId");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("ServerBackup.Data.Entities.SnapshotPathEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("SnapshotPaths");
                });

            modelBuilder.Entity("ServerBackup.Data.Entities.BlobEntity", b =>
                {
                    b.HasOne("ServerBackup.Data.Entities.PackEntity", "Pack")
                        .WithMany("Blobs")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("ServerBackup.Data.Entities.JobLogEntity", b =>
                {
                    b.HasOne("ServerBackup.Data.Entities.JobEntity", "Job")
                        .WithMany("Logs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ServerBackup.Data.Entities.SnapshotPathEntity", b =>
                {
                    b.HasOne("ServerBackup.Data.Entities.SnapshotEntity", "Snapshot")
                        .WithMany("Paths")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("ServerBackup.Data.Entities.JobEntity", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("ServerBackup.Data.Entities.PackEntity", b =>
                {
                    b.Navigation("Blobs");
                });

            modelBuilder.Entity("ServerBackup.Data.Entities.SnapshotEntity", b =>
                {
                    b.Navigation("Paths");
                });
#pragma warning restore 612, 618
        }
    }
}
