<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ServerBackup.Core\ServerBackup.Core.csproj" />
    <ProjectReference Include="..\ServerBackup.Data\ServerBackup.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AlphaVSS" Version="2.0.3" />
    <PackageReference Include="Cronos" Version="0.13.0" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.10" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.10" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
